---
# Tự động hóa cấu hình nền tảng (Base Configuration)
- name: BASE | Configure Domain Name
  cisco.ios.ios_system:
    domain_name: uit.edu.vn

- name: BASE | Enable Global Password Encryption
  cisco.ios.ios_config:
    lines:
      - service password-encryption

- name: BASE | Configure Legal Warning Banner
  cisco.ios.ios_banner:
    banner: login
    text: |
      **************************************************************
      * WARNING: UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED. *
      * THIS SYSTEM IS MANAGED BY ANSIBLE AUTOMATION (DEV-OPS).    *
      **************************************************************
    state: present