---
- name: Backup Running Config of Cisco Routers
  hosts: cisco_routers
  gather_facts: false
  tasks:
    - name: Get running config
      cisco.ios.ios_command:
        commands: show running-config
      register: config_output

    - name: Save config to local file
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "./backups/{{ inventory_hostname }}_config.txt"
      delegate_to: localhost